name: TypeScript Build and Test

on:
  push:
    branches: [main, "ci-test*"]
  pull_request_target:
    branches: [main, "ci-test*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Change to 'stacks' directory
        run: cd stacks

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libxtst-dev

      - name: Update Node.js and npm
        run: |
          npm install -g npm@latest

      - name: Update robotjs
        run: |
          npm install robotjs@latest

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # You can specify your Node.js version here

      - name: Install Dependencies
        run: npm install

      - name: Fetch Latest Changes
        run: git fetch

      - name: Run Jest on Modified Folder
        run: npx jest --onlyChanged
